apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-gateway-deployment
  namespace: default
  labels:
    app: mall-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-gateway
  template:
    metadata:
      labels:
        app: mall-gateway
    spec:
      containers:
        - name: mall-gateway
          # 指定镜像源
          image: 192.168.124.10:5000/mall/mall-gateway:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
#          command: ["/bin/bash", "-ce", "tail -f /dev/null"]
          ports:
            - containerPort: 8201
          imagePullSecrets:
            - name: registry-secret
          env:
            # 指定环境
            - name: spring.profiles.active
              value: prod
            # 指定时区
            - name: TZ
              value: Asia/Shanghai
            # 指定Nacos地址
            - name: spring.cloud.nacos.discovery.server-addr
              value: http://192.168.124.10:8848
            - name: spring.cloud.nacos.config.server-addr
              value: http://192.168.124.10:8848
      volumes:
        - name: log-volume
          hostPath:
            path: D:\project\tools\mallDeploy\dockerDir\mydata\app\mall-gateway\logs
            type: DirectoryOrCreate